import js from "@eslint/js";

export default [
  {
    ignores: ["**/*.min.js"],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: {
        // Espruino pins
        A0: "readonly", A1: "readonly", A2: "readonly", A3: "readonly",
        A4: "readonly", A5: "readonly", A6: "readonly", A7: "readonly",
        A8: "readonly", A9: "readonly", A10: "readonly", A11: "readonly",
        A12: "readonly", A13: "readonly", A14: "readonly", A15: "readonly",
        B0: "readonly", B1: "readonly", B2: "readonly", B3: "readonly",
        B4: "readonly", B5: "readonly", B6: "readonly", B7: "readonly",
        B8: "readonly", B9: "readonly", B10: "readonly", B11: "readonly",
        B12: "readonly", B13: "readonly", B14: "readonly", B15: "readonly",
        C0: "readonly", C1: "readonly", C2: "readonly", C3: "readonly",
        C4: "readonly", C5: "readonly", C6: "readonly", C7: "readonly",
        C8: "readonly", C9: "readonly", C10: "readonly", C11: "readonly",
        C12: "readonly", C13: "readonly",
        P0: "readonly", P1: "readonly", P2: "readonly", P3: "readonly",
        P4: "readonly", P5: "readonly", P6: "readonly", P7: "readonly",
        P8: "readonly",
        // Espruino hardware
        analogRead: "readonly", analogWrite: "readonly",
        digitalPulse: "readonly", digitalRead: "readonly", digitalWrite: "readonly",
        pinMode: "readonly", shiftOut: "readonly",
        setWatch: "readonly", clearWatch: "readonly",
        changeInterval: "readonly",
        peek16: "readonly", peek32: "readonly", poke16: "readonly", poke32: "readonly",
        // Espruino peripherals
        I2C: "readonly", I2C1: "readonly", I2C2: "readonly", I2C3: "readonly",
        SPI: "readonly", SPI1: "readonly", SPI2: "readonly", SPI3: "readonly",
        Serial: "readonly", Serial1: "readonly", Serial2: "readonly", Serial3: "readonly",
        SDA: "readonly", SCL: "readonly",
        PrimaryI2C: "readonly", PrimarySerial: "readonly",
        // Espruino misc
        Bluetooth: "readonly", BTN: "readonly",
        E: "readonly",
        Graphics: "readonly",
        HIGH: "readonly", LOW: "readonly",
        LED1: "readonly", LED2: "readonly", LED3: "readonly",
        LoopbackA: "readonly", LoopbackB: "readonly",
        NRF: "readonly", OneWire: "readonly",
        Pin: "readonly",
        print: "readonly",
        getTime: "readonly",
        // Timers
        setTimeout: "readonly", clearTimeout: "readonly",
        setInterval: "readonly", clearInterval: "readonly",
        // Node
        process: "readonly",
        // Browser/stdlib
        atob: "readonly", btoa: "readonly",
        url: "readonly",
      },
    },
    rules: {
      "accessor-pairs": "error",
      "array-callback-return": "error",
      "arrow-spacing": ["error", { after: true, before: true }],
      "func-name-matching": "error",
      "generator-star-spacing": "error",
      "id-denylist": "error",
      "id-match": "error",
      "implicit-arrow-linebreak": ["error", "beside"],
      "jsx-quotes": "error",
      "lines-between-class-members": ["error", "always"],
      "max-classes-per-file": "error",
      "max-nested-callbacks": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-await-in-loop": "error",
      "no-caller": "error",
      "no-continue": "error",
      "no-div-regex": "error",
      "no-duplicate-imports": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-global-assign": "error",
      "no-floating-decimal": "error",
      "no-implied-eval": "error",
      "no-inner-declarations": ["error", "functions"],
      "no-invalid-this": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-misleading-character-class": "error",
      "no-multi-str": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-object": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-proto": "error",
      "no-prototype-builtins": "error",
      "no-restricted-globals": "error",
      "no-restricted-imports": "error",
      "no-restricted-modules": "error",
      "no-restricted-properties": "error",
      "no-restricted-syntax": "error",
      "no-return-assign": "error",
      "no-return-await": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-shadow-restricted-names": "error",
      "no-template-curly-in-string": "error",
      "no-unneeded-ternary": ["error", { defaultAssignment: true }],
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^e$" }],
      "no-useless-assignment": "off",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-void": "error",
      "no-whitespace-before-property": "error",
      "no-with": "error",
      "nonblock-statement-body-position": ["error", "any"],
      "padding-line-between-statements": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-spread": "error",
      "prefer-spread": "error",
      "require-atomic-updates": "error",
      "require-await": "error",
      "rest-spread-spacing": "error",
      "semi-style": ["error", "last"],
      "sort-imports": "error",
      "strict": ["error", "never"],
      "symbol-description": "error",
      "template-curly-spacing": ["error", "never"],
      "template-tag-spacing": "error",
      "unicode-bom": ["error", "never"],
      "wrap-regex": "error",
      "yield-star-spacing": "error",
    },
  },
];
